### ISSUE TITLE
Vigenette: render as a pdf

### ISSUE THREAD

**Issue by ByrumLab** [ByrumLab/proteoDA#201]

**Comment by tjthurman** [comment]
I've been working on getting the vignettes to not throw R CMD check error and also been trying to get them to render as PDFs. I think I've got the vignette working within the R package infrastructure, but I'm having issues getting it to build PDFs. Apparently this is a common issue: PDF vignettes are common with older packages, when Sweave was the main thing used for converting R code to other documents, but newer packages tend to just use HTML.

In looking at the packages I currently have in my session, the majority use HTML, the bioconductor packages tend to use PDF, and none use both. Given that, and that rendering HTML vignettes is much easier, can we close this issue and stick with HTML only?

**Comment by ByrumLab** [comment]
html is fine. Others example from JOSS had both html and pdf or just pdf. Then you can read it in the git repo without downloading. Can we see the html file without downloading?

**Comment by tjthurman** [comment]
The way I have it at the moment, the html file is ignored by Git. We could change that, but we'd have to remember to locally rebuild the vignette and update it whenever we make a change, otherwise the .html file on GitHub could be out of sync with the package. Usually, vignettes get made (and thus checked) when the package gets built: either when someone installs a binary package from CRAN (CRAN builds the vignettes) or when they build the package locally when installing a source package from CRAN or GitHub, so the vignette and the rest of the package are automatically in sync.

I tried checking JOSS real quick and didn't find any R packages with PDF vignettes on Github. Do you remember what package it was, I could take a look and see if I can use their code as a template

**Comment by ByrumLab** [comment]
Let's stick with html only. I was looking at these two different ones. 

https://github.com/darcyj/pd_assemb/tree/master/tutorial 
https://github.com/qiime2/q2-sample-classifier

**Comment by tjthurman** [comment]
HTML only it is! Will close this issue.
